substitutions:
   device_name: esp_d1m_03
   device_name_upper: ESP Wemos 03
   device_icon: mdi:chip
   device_ip: 192.168.1.144


esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  includes:
    - RainGaugeSensor.h

wifi:
  ssid: !secret ssid_wifi
  password: !secret pwd_wifi
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 1.1.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name_upper} Fallback Hotspot
    password: !secret pwd_wifi_backupap

captive_portal:

# Enable logging
logger:

# Enable Web Server (optional)
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret pwd_esp_api_ota

ota:
  password: !secret pwd_esp_api_ota

############################################################################################
############################################################################################

# Temperature Sensors:
dallas:
  - pin: D2 #D2 for d1_mini


# The following can be omitted 
#  - platform: restart
#    name: ${devicename} restart 

binary_sensor:
  - platform: status
    name: ${device_name} status

sensor:
  - platform: wifi_signal
    name: ${device_name} wifi signal
    update_interval: 600s
 
  - platform: uptime
    name: ${device_name} uptime
  
  # Temperature Sensors
  - platform: dallas
    address: 0x510119270xxxxxx
    name: ${device_name} temp
    
  - platform: custom
    lambda: |-
      auto RainGauge = new RainGaugeSensor();
      App.register_component(RainGauge);
      return {RainGauge->rain_daily_sensor,RainGauge->rain_total_sensor};
      
    sensors:
    - name: "Rain Daily Sensor"
      unit_of_measurement: mm
      accuracy_decimals: 2
    - name: "Rain Total Sensor"
      unit_of_measurement: mm
      accuracy_decimals: 1
